### ISSUE TITLE
No padding for scroll bar when scrolling to the right with grouping

### ISSUE THREAD

**Issue by salimnanji** [free-jqgrid/jqGrid#161]
When you have a grid with grouping, a set width, and columns where there is a horizontal scroll bar, the grid not set padding-right for the scrollbar in ui-jqgrid-htable. 

Open up groupings until the rows take up the height of the grid, and then scroll to the right

See fiddle: http://jsfiddle.net/LLx2hq54/2/

**Comment by OlegKi** [comment]
Thank you for the bug report. I will modify the code of `groupingToggle` soon by adding additional calls of `fixScrollOffsetAndhBoxPadding` and `setGridWidth`. You can already test the results on the here: http://jsfiddle.net/OlegKi/LLx2hq54/3/

**Comment by OlegKi** [comment]
Th problem should be fixed after posting the last fixes today. Please verify this and close the issue if everything is OK now.

**Comment by salimnanji** [comment]
Still does not work in my project. I'll try to make a fiddle that models why it is still not working.

**Comment by OlegKi** [comment]
Just compare your code with http://jsfiddle.net/OlegKi/e3ouywqs/4/ where you can add `width: 300` or `maxHeight: 300`. The `padding-right` will be correctly interested dynamically. Please verify that you use **the latest sources** of free jqGrid and not some cached versions (press F5 in web browser).

In any way the demo which reproduces the problem using `http://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js` is required. I can fix only the problem which I can reproduce.

**Comment by salimnanji** [comment]
Used the latest sources. I see padding-right: 0px as the inline element style on chrome instead of 20px as the css shows.

![padding](https://cloud.githubusercontent.com/assets/12036621/10729723/b5bfcd98-7bc1-11e5-829b-ae23d06ca757.png)

**Comment by OlegKi** [comment]
I can only repeat that *you should provide the demo* which reproduces the problem. I wrote you that the `padding-right` will be set **dynamically**. It the beginning have the grid `padding-right: 0` later, for example on expanding the group, it will be more visible rows, the vertical scrollbar appears and the `padding-right` will be increased to the width of the scrollbar. So the above picture is absolutely correct. After expanding free jqGrid calls `fixScrollOffsetAndhBoxPadding();` method [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.grouping.js#L260) (try `$("#list")[0].fixScrollOffsetAndhBoxPadding();` in any part of your code), which set `padding-right` (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.base.js#L968)).

By the way the width of scrollbar in Chrome depend on the zoom factor. If one uses 100% zoom, then `padding-right: 21px;`, on zoom 150% one will see `padding-right: 14px;`, on zoom 200% one will see `padding-right: 10px;` and so on. You can try the demo http://jsfiddle.net/OlegKi/e3ouywqs/8/ where I added the code
```JavaScript
$(window).resize(function () {
    //$grid[0].fixScrollOffsetAndhBoxPadding();
   $grid.triggerHandler("jqGridResetFrozenHeights", [{
       header: {
           resizeDiv: true,      // recalculate the position and the height of hDiv
           resizedRows: {
               iRowStart: -1, // -1 means don't recalculate heights of every row inside of hDiv
               iRowEnd: -1
           }
       },
       resizeFooter: true,       // recalculate the position and the height of sDiv
       body: {
           resizeDiv: true,      // recalculate the position and the height of bDiv
           resizedRows: {
               iRowStart: -1, // -1 means don't recalculate heights of every row inside of bDiv
               iRowEnd: -1
           }
       }
   }]);
});
```
Changing the zoom on the page will change position, width and height of frozen divs and all will looks OK. It calls `fixScrollOffsetAndhBoxPadding()` internally so the `padding-right` will be adjusted on zoom (in the vertical scrollbar exist). You can remove (comment) `$grid.triggerHandler("jqGridResetFrozenHeights",...)` and uncomment the line `$grid[0].fixScrollOffsetAndhBoxPadding();`, which only adjust `padding-right`. You will see changing of `padding-right` on zooming the page, but the position of frozen dives could be not OK after zooming. All works as expected.

So I really need **the demo** which reproduce the problem which you reports.

**Comment by salimnanji** [comment]
Currently working on getting a demo. It's taking me a while to narrow it down and get the same behaviour on a fiddle. 

As of now I know that it only happens if groupCollapse: true. If I set groupCollapse: false the scroll bar shows again.

I'll keep you updated.

**Comment by salimnanji** [comment]
Seems to happen when I call"

**Comment by salimnanji** [comment]
It was an issue on my end with one of my specific customizations. Sorry about that!

Closing issue.

**Comment by OlegKi** [comment]
It's good new. I'll make some more tests and then will publish version 4.10.0.

By the way I would recommend you to optimize the code which you posed. You can use very simple to understand code:
```JavaScript
var p = table.jqGrid("getGridParam"); // get REFERENCE to internal parameters
p.data = gridData;
table.trigger('reloadGrid');
```
The line `table.jqGrid('clearGridData')` do a little more as just cleaning the `data` array. The next line `table.jqGrid('setGridParam', {data: gridData})` makes copy of input parameter by usage of `$.extend(true, self.p, newParams);` which can be relatively slowly for arrays. Setting of `p.data = gridData;` is much more effectively. the only thing which you need don't forget is that you set `p.data` as **reference** to `gridData`. You should be carefully in modification of the array. You can use
```JavaScript
var p = table.jqGrid("getGridParam"); // get REFERENCE to internal parameters
p.data = gridData.slice(); // make copy of gridData array
table.trigger('reloadGrid');
```
instead. One will use the same objects for the rows (for the elements of `p.data` array). If you **really need to make deep copy** of `gridData` then you can do the following
```JavaScript
var p = table.jqGrid("getGridParam"); // get REFERENCE to internal parameters
p.data = []; // better as clearGridData
table.jqGrid('setGridParam', {data: gridData}).trigger('reloadGrid');
```
The `setGridParam` **extends** the existing array. So the empty array will be *extended* to the same as `gridData` finally.

**Comment by salimnanji** [comment]
Will do, thank you!
